version: '3'
services:
    web:
        build: .
        ports:
            - '8081:8080'
        volumes:
            - .:/app
            - '/app/node_modules'
        depends_on:
            - 'db'
    db:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
